### PR TITLE
Updated to patch2 of plugin helpers

### PR DESCRIPTION
**Pull request by Kikketer**
Updated to patch2 for the plugin helpers

### CODE REVIEW

**Comment by w33ble** [comment]
Thanks for the PR. 

5.x still doesn't handle the build correctly though. I think if we're upgrading the plugin helpers, we should just upgrade to 6.0.0. @spalger thoughts?

**Comment by Kikketer** [comment]
This version of the helpers seems to work when building for kibana 5.1.1. It's just one of the things I need to change immediately after doing the 'yo' command.

**Comment by w33ble** [comment]
@Kikketer would you mind testing one of the more stable releases in the 5.x chain? I could just push a simple update through, but I rather not rely on a patch version. 5.1.1 or 5.2.0 should still be functionally similar, they just added some more advanced options. 6.0.0 brings a much larger change to how builds are created.

**Comment by Kikketer** [comment]
@w33ble Thanks, I'll be testing this with 5.2.0 tomorrow since my team has moved to that version as of last week.
The update really is to just get the helpers version up to speed with the latest.  `patch2` is the latest plugin helper which solved some of the issues I was having during the build.  Since I'm running (and packaging for release) my current plugins on 5.2.0 using the same `patch2` version of the plugin helpers, I assume that means it's working with that version of the helpers.

**Comment by w33ble** [comment]
@Kikketer Fair enough. Looking at the releases, `patch2` is just a patch release, and in my opinion, should have been a numbered patch release. Maybe I'll push a `5.0.2` release that's based on the same commit and get this merged.

Still would like to hear if 5.2.0 works correctly for you, and just bump to that version.

**Comment by Kikketer** [comment]
@w33ble I've created a new plugin using this update and it's working fine with version 5.2.0 of kibana.  The `npm run start` within the generated plugin works along with `npm run build`

I forget exactly what @spalger and I had discussed and fixed with that patch update but I know it was critical to get the plugin to generate the correct file structure for use with 5.x (update was done with 5.1 and now works as well with 5.2).

**Comment by spalger** [comment]
Thanks @Kikketer, I just bumped them to the latest version, 6.0. If you have any trouble let me know

**Pull request closed without merging**
